config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "leagues/accept_invite"
  post "leagues/add_user_to_league"
  resources :leagues
  resources :games
  resources :syncs
  resources :score_syncs
  
  get "users/sign_up"
  get "users/sign_in"
  get "users/about_page", as: :about_page

  post '/score_syncs/manualUpdate', to: 'score_syncs#manualUpdate', as: 'manualUpdate'
  
  get "games/picks/:league_id", to: 'games#picks', as: 'games_picks'
  post "games/submit_picks/:league_id", to: "games#submit_picks", as: "games_submit_picks"
  get "games/show_picks/:league_id/:user_id", to: 'games#show_picks', as: "show_picks"
  get "games/show_all_picks/:league_id", to: 'games#show_all_picks', as: "show_all_picks"
  
  get 'leagues/add_announcement/:league_id', to: 'leagues#add_announcement', as: 'leagues_add_announcements'
  get 'leagues/set_tiebreaker/:league_id', to:'leagues#set_tiebreaker', as: 'leagues_set_tiebreaker'
  post "games/submit_tiebreaker/:league_id", to: "leagues#submit_tiebreaker", as: "leagues_submit_tiebreaker"
  post 'leagues/create_announcement/:league_id', to: 'leagues#create_announcement', as: 'create_announcement'
end

app/models/league.rb
class League < ActiveRecord::Base
  belongs_to :commissioner
  belongs_to :current_leader
  belongs_to :user1
  belongs_to :user2
  belongs_to :user3
  belongs_to :user4
  belongs_to :user5
  belongs_to :user6
  belongs_to :user7
  belongs_to :user8
  belongs_to :user9
  belongs_to :user10
  belongs_to :user11
  belongs_to :user12
  belongs_to :user13
  belongs_to :user14
  belongs_to :user15
  belongs_to :user16
  belongs_to :user17
  belongs_to :user18
  belongs_to :user19
  belongs_to :user20
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :set_league, only: [:show, :edit, :update, :destroy]

  def index
    @leagues = League.all
  end
  
  def new
    @league = League.new
  end

  def show
    if @league == nil then
      flash[:notice] = "Oops, that league doesn't exist!"
      redirect_to leagues_path
      return
    end
    
    week = Time.now.strftime('%U')
        
    @tiebreaker = Tiebreaker.where(league_id: @league.id,  week: week).take
    
    #@tiebreaker_game = Game.where(id: tiebreaker.game_id).take
    
    @infos = [];
    @infos << { :title => "Commissioner", :data => User.find(@league.commissioner_id).email };
    @infos << { :title => "Conference", :data => @league.conference_settings };
    @infos << { :title => "Picks Per Week", :data => @league.number_picks_settings };
    
    # list of members
    memberIds = [];
    memberIds << @league.user1_id unless @league.user1_id == nil
    memberIds << @league.user2_id unless @league.user2_id == nil
    memberIds << @league.user3_id unless @league.user3_id == nil
    memberIds << @league.user4_id unless @league.user4_id == nil
    memberIds << @league.user5_id unless @league.user5_id == nil
    memberIds << @league.user6_id unless @league.user6_id == nil
    memberIds << @league.user7_id unless @league.user7_id == nil
    memberIds << @league.user8_id unless @league.user8_id == nil
    memberIds << @league.user9_id unless @league.user9_id == nil
    memberIds << @league.user10_id unless @league.user10_id == nil
    memberIds << @league.user11_id unless @league.user11_id == nil
    memberIds << @league.user12_id unless @league.user12_id == nil
    memberIds << @league.user13_id unless @league.user13_id == nil
    memberIds << @league.user14_id unless @league.user14_id == nil
    memberIds << @league.user15_id unless @league.user15_id == nil
    memberIds << @league.user16_id unless @league.user16_id == nil
    memberIds << @league.user17_id unless @league.user17_id == nil
    memberIds << @league.user18_id unless @league.user18_id == nil
    memberIds << @league.user19_id unless @league.user19_id == nil
    memberIds << @league.user20_id unless @league.user20_id == nil
        
    @players = [];
    i = 1;
    memberIds.each do |user_id|
      user = User.find(user_id)
      @players << {
        :id => user.id,
        :rank => i,
        :name => user.first_name + " " + user.last_name,
        :points => "NA"
      }
      i = i + 1;
    end
    
    #winnersIds = [];
    #winnersIds << 2;
    
    @season_weekly_winners = []
    year = Time.now.strftime('%Y').to_i
    i = 1;
    weekly_winners=WeeklyWinner.where(league_id: @league.id, year: year )
    weekly_winners.each do |week_winner|
      (week_winner.winners.size).times do |winner_index|
        user = User.find(week_winner.winners[winner_index]);
        @season_weekly_winners << {
          :week_number => i,
          :name => user.first_name + " " + user.last_name,
          :wins => (LeaguePick.where(user_id: user.id, league_id: @league.id, week: week_winner.week)[0]).wins,
          :losses => (LeaguePick.where(user_id: user.id, league_id: @league.id, week: week_winner.week)[0]).losses,
          :pushes => (LeaguePick.where(user_id: user.id, league_id: @league.id, week: week_winner.week)[0]).pushes
        }
      end
      i = i + 1;
    end
    
    @standings = Hash.new
    i = 1;
    
    @updated_standings=[]
    if @season_weekly_winners == []
      @updated_standings = @players
    else
      all_year_league_picks=LeaguePick.where(league_id: @league.id)
      all_year_league_picks.each do |league_pick|
        if(!(@standings.has_key?(league_pick.user_id)))
          @standings[league_pick.user_id]={:wins => league_pick.wins, :losses => league_pick.losses, :pushes => league_pick.pushes}
        else
          temp=@standings
          if temp[league_pick.user_id][:wins] != nil
            @standings[league_pick.user_id]={:wins => (temp[league_pick.user_id][:wins] + league_pick.wins), :losses => (temp[league_pick.user_id][:losses] + league_pick.losses), :pushes => (temp[league_pick.user_id][:pushes] + league_pick.pushes)} 
          end
        end
      end
      @standings=@standings.sort_by{|k,v| [v[:wins], v[:pushes]]}.reverse!
  
      lastwins=0
      lastlosses=0
      lastpushes=0
      lastrank=0
      @standings.each do |entry|
        user = User.find(entry[0]);
        if(lastwins==entry[1][:wins] && lastlosses==entry[1][:losses] && entry[1][:pushes])
          rank=lastrank
        else
          rank=i
        end
        i=i+1
        @updated_standings << {
          :rank => rank,
          :name => user.first_name + " " + user.last_name,
          :wins => entry[1][:wins],
          :losses =>entry[1][:losses],
          :pushes =>entry[1][:pushes],
          :id => user.id
        }
        
        lastrank=rank
        
        lastwins=entry[1][:wins]
        lastlosses=entry[1][:losses]
        lastpushes=entry[1][:pushes]
      end
      
    end
      #weekly_winners.each do |week_winner|
     # (week_winner.winners.size).times do |winner_index|
      #  user = User.find(week_winner.winners[winner_index]);
       # @season_weekly_winners << {
        #  :week_number => i,
         # :name => user.first_name + " " + user.last_name,
          #:wins => (LeaguePick.where(user_id: user.id, week: week_winner.week)[0]).wins,
          #:losses => (LeaguePick.where(user_id: user.id, week: week_winner.week)[0]).losses,
        #  :pushes => (LeaguePick.where(user_id: user.id, week: week_winner.week)[0]).pushes
        #}
      #end
      #i = i + 1;
    #end
    
    week = Time.now.strftime('%U')
    @league_pick = LeaguePick.where(user_id: current_user.id, league_id: @league.id, week: week).take
    
    @show_announcements = false
    @show_announcements = true unless @league.commissioner_id != current_user.id
    
  end

  def edit
    if @league == nil then
      flash[:notice] = "Oops, that league doesn't exist!"
      redirect_to leagues_path
      return
    end
    @infos = [];
    @infos << { :title => "Commissioner", :data => User.find(@league.commissioner_id).email };
    @infos << { :title => "Conference", :data => @league.conference_settings };
    @infos << { :title => "Picks Per Week", :data => @league.number_picks_settings };
    
    # list of members
    memberIds = [];
    memberIds << @league.user1_id unless @league.user1_id == nil
    memberIds << @league.user2_id unless @league.user2_id == nil
    memberIds << @league.user3_id unless @league.user3_id == nil
    memberIds << @league.user4_id unless @league.user4_id == nil
    memberIds << @league.user5_id unless @league.user5_id == nil
    memberIds << @league.user6_id unless @league.user6_id == nil
    memberIds << @league.user7_id unless @league.user7_id == nil
    memberIds << @league.user8_id unless @league.user8_id == nil
    memberIds << @league.user9_id unless @league.user9_id == nil
    memberIds << @league.user10_id unless @league.user10_id == nil
    memberIds << @league.user11_id unless @league.user11_id == nil
    memberIds << @league.user12_id unless @league.user12_id == nil
    memberIds << @league.user13_id unless @league.user13_id == nil
    memberIds << @league.user14_id unless @league.user14_id == nil
    memberIds << @league.user15_id unless @league.user15_id == nil
    memberIds << @league.user16_id unless @league.user16_id == nil
    memberIds << @league.user17_id unless @league.user17_id == nil
    memberIds << @league.user18_id unless @league.user18_id == nil
    memberIds << @league.user19_id unless @league.user19_id == nil
    memberIds << @league.user20_id unless @league.user20_id == nil
        
    @players = [];
    i = 1;
    memberIds.each do |user_id|
      user = User.find(user_id);
      @players << {
        :id => user.id,
        :rank => i,
        :name => user.first_name + " " + user.last_name,
        :points => "NA"
      }
      i = i + 1;
    end
  end

  def create
    @league = League.new(league_params)
    @this_user=User.find(current_user.id)
    @league.commissioner_id=current_user.id
    @league.user1_id=current_user.id
    @league.number_members = 1
    @league.bowlSeason=(League.all.take).bowlSeason
    
    if @this_user.num_leagues >= 5
      flash[:notice]="League not created because you have reached max number of leagues!!"
      redirect_to authenticated_root_path
      return
    end
    
    respond_to do |format|
      if @league.save
        
        if @this_user.league1_id == nil
          @this_user.league1_id = @league.id
          @this_user.num_leagues=@this_user.num_leagues+1
        elsif @this_user.league2_id == nil
          @this_user.league2_id = @league.id
          @this_user.num_leagues=@this_user.num_leagues+1
        elsif @this_user.league3_id == nil
          @this_user.league3_id = @league.id
          @this_user.num_leagues=@this_user.num_leagues+1
        elsif @this_user.league4_id == nil
          @this_user.league4_id = @league.id
          @this_user.num_leagues=@this_user.num_leagues+1
        elsif @this_user.league5_id == nil
          @this_user.league5_id = @league.id
          @this_user.num_leagues=@this_user.num_leagues+1
        end

        @this_user.save!
        
        
        format.html { redirect_to @league }
        format.json { render :show, status: :created, location: @league }
        array_of_emails = params[:email_list].split(',')
        array_of_emails.each {|x| UserMailer.league_invite(x,@league.id).deliver_now}  #SEND EMAIL HERE
      else
        format.html { render :new }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @infos = [];
    @infos << { :title => "Commissioner", :data => User.find(@league.commissioner_id).email };
    @infos << { :title => "Conference", :data => @league.conference_settings };

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/views/leagues/_form.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :league_name %> 
    <%= f.text_field :league_name %>
  </div>
  <div class="field">
    <%= f.label :commissioner_id %> 
    <%= f.text_field :commissioner_id %>
  </div>
  <div class="field">
    <%= f.label :current_leader_id %> 
    <%= f.text_field :current_leader_id %>
  </div>
  <div class="field">
    <%= f.label :conference_settings %> 
    <%= f.text_field :conference_settings %>
  </div>
  <div class="field">
    <%= f.label :number_picks_settings %> 
    <%= f.number_field :number_picks_settings %>
  </div>
  <div class="field">
    <%= f.label :number_members %> 
    <%= f.number_field :number_members %>
  </div>
  <div class="field">
    <%= f.label :user1_id %> 
    <%= f.text_field :user1_id %>
  </div>
  <div class="field">
    <%= f.label :user2_id %> 
    <%= f.text_field :user2_id %>
  </div>
  <div class="field">
    <%= f.label :user3_id %> 
    <%= f.text_field :user3_id %>
  </div>
  <div class="field">
    <%= f.label :user4_id %> 
    <%= f.text_field :user4_id %>
  </div>
  <div class="field">
    <%= f.label :user5_id %> 
    <%= f.text_field :user5_id %>
  </div>
  <div class="field">
    <%= f.label :user6_id %> 
    <%= f.text_field :user6_id %>
  </div>
  <div class="field">
    <%= f.label :user7_id %> 
    <%= f.text_field :user7_id %>
  </div>
  <div class="field">
    <%= f.label :user8_id %> 
    <%= f.text_field :user8_id %>
  </div>
  <div class="field">
    <%= f.label :user9_id %> 
    <%= f.text_field :user9_id %>
  </div>
  <div class="field">
    <%= f.label :user10_id %> 
    <%= f.text_field :user10_id %>
  </div>
  <div class="field">
    <%= f.label :user11_id %> 
    <%= f.text_field :user11_id %>
  </div>
  <div class="field">
    <%= f.label :user12_id %> 
    <%= f.text_field :user12_id %>
  </div>
  <div class="field">
    <%= f.label :user13_id %> 
    <%= f.text_field :user13_id %>
  </div>
  <div class="field">
    <%= f.label :user14_id %> 
    <%= f.text_field :user14_id %>
  </div>
  <div class="field">
    <%= f.label :user15_id %> 
    <%= f.text_field :user15_id %>
  </div>
  <div class="field">
    <%= f.label :user16_id %> 
    <%= f.text_field :user16_id %>
  </div>
  <div class="field">
    <%= f.label :user17_id %> 
    <%= f.text_field :user17_id %>
  </div>
  <div class="field">
    <%= f.label :user18_id %> 
    <%= f.text_field :user18_id %>
  </div>
  <div class="field">
    <%= f.label :user19_id %> 
    <%= f.text_field :user19_id %>
  </div>
  <div class="field">
    <%= f.label :user20_id %> 
    <%= f.text_field :user20_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leagues/_leagueForm.html.erb
<%= form_for(@league) do |f| %>
  <% if @league.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@league.errors.count, "error") %> prohibited this league from being saved:</h2>

      <ul>
      <% @league.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="span4">
        <div class="field">
        <%= f.label :league_name %>
        <%= f.text_field :league_name %>
      </div>
      <div class="field">
       <br> <%= f.label :conference_settings %>
        <%= f.select :conference_settings, 
        options_for_select({ "FBS" => "FBS", "SEC" => "SEC","BIG 10" => "Big 10", "Big 12" => "Big 12","ACC" => "ACC", "American Athletic Conference" => "American Athletic Conference","Conference USA" => "Conference USA", "Mid-American Conference" => "Mid-American Conference", "Mountain West Conference" => "Mountain West Conference", "PAC 12" => "PAC 12", "Sun Belt" => "Sun Belt" },"FBS" => "FBS") %>
      </div>
      <div class="field">
        <br><%= f.label :number_picks_settings %>
        <%= f.select :number_picks_settings, 
        options_for_select((1..20),1) %>
      </div>
      <div class="field">
        <br><%= label_tag "Enter Emails of Members Separated by Commas"%>
        <%= text_area_tag "email_list"%>
      </div>
      <div class="actions">
        <%= f.submit :id => "work"%>
      </div>
    </div>
    <div class="span8">
      <%= image_tag "Drawing.png", :alt => "Logo", :class => "login_page_logo" %>
    </div>
    
  </div>
  
<% end %>

app/views/leagues/accept_invite.html.erb
<% if user_signed_in? %>
    <%= button_to "Accept Invite", action: "add_user_to_league",:league_id=>params[:param1] %>
<% end %> 

app/views/leagues/add_announcement.html.haml
!!!
%html
  %head
    :javascript
        $(document).ready(function() {
          $("#start_time").datepicker({
                minDate: "+0D", 
                maxDate: "+6M",
                dateFormat: "yy-mm-dd"
            });
            
          $("#end_time").datepicker({
                minDate: "+0D", 
                maxDate: "+6M",
                dateFormat: "yy-mm-dd"
            });
        });
        
    %div.jumbotron
      %h2 Add Announcement to
      %h2= @league.league_name
    
    %div.row
      %div.span12
        %p.header This announcement will be visible to any users signed up for your league.

      %div.span12
        = form_tag create_announcement_path(@league.id) do 
          %br 
          %br
          = text_field :text, 'announcement', class: "large_text_entry", :id => 'announcement'
          %br
          = label :start_time, 'Start Date'
          = text_field :text, 'start_time', class: "jquery-ui-date", :id => 'start_time'
          %br
          = label :end_time, 'End Date'
          = text_field :text, 'end_time', class: "jquery-ui-date", :id => 'end_time'
          %br
          = submit_tag 'Create Announcement', class: "btn", :id => 'create'

app/views/leagues/edit.html.erb
<h1>Editing League</h1>

<%= render 'leagueEditForm' %>

<%= link_to 'Show', @league %> |
<%= link_to 'Back', leagues_path %>

app/views/leagues/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leagues</h1>

<table>
  <thead>
    <tr>
      <th>League name</th>
      <th>Commissioner</th>
      <th>Current leader</th>
      <th>Conference settings</th>
      <th>Number picks settings</th>
      <th>Number members</th>
      <th>User1</th>
      <th>User2</th>
      <th>User3</th>
      <th>User4</th>
      <th>User5</th>
      <th>User6</th>
      <th>User7</th>
      <th>User8</th>
      <th>User9</th>
      <th>User10</th>
      <th>User11</th>
      <th>User12</th>
      <th>User13</th>
      <th>User14</th>
      <th>User15</th>
      <th>User16</th>
      <th>User17</th>
      <th>User18</th>
      <th>User19</th>
      <th>User20</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leagues.each do |league| %>
      <tr>
        <td><%= league.league_name %></td>
        <td><%= User.find(league.commissioner_id).email %></td>
        <td><%= league.current_leader_id %></td>
        <td><%= league.conference_settings %></td>
        <td><%= league.number_picks_settings %></td>
        <td><%= league.number_members %></td>
        <td><%= if league.user1_id != nil
                  User.find(league.user1_id).email 
                end
                  %></td>
        <td><%= if league.user2_id != nil 
                  User.find(league.user2_id).email
                end
                  %></td>
        <td><%= if league.user3_id != nil
                  User.find(league.user3_id).email 
                end %></td>
        <td><%=if league.user4_id != nil
                  User.find(league.user4_id).email 
                end %></td>
        <td><%= if league.user5_id != nil
                  User.find(league.user5_id).email 
                end %></td>
        <td><%= if league.user6_id != nil
                  User.find(league.user6_id).email 
                end %></td>
        <td><%= if league.user7_id != nil
                  User.find(league.user7_id).email 
                end %></td>
        <td><%= if league.user8_id != nil
                  User.find(league.user8_id).email 
                end %></td>
        <td><%= if league.user9_id != nil
                  User.find(league.user9_id).email 
                end %></td>
        <td><%= if league.user10_id != nil
                  User.find(league.user10_id).email 
                end %></td>
        <td><%= if league.user11_id != nil
                  User.find(league.user11_id).email 
                end %></td>
        <td><%= if league.user12_id != nil
                  User.find(league.user12_id).email 
                end %></td>
        <td><%= if league.user13_id != nil
                  User.find(league.user13_id).email 
                end %></td>
        <td><%= if league.user14_id != nil
                  User.find(league.user14_id).email 
                end %></td>
        <td><%= if league.user15_id != nil
                  User.find(league.user15_id).email 
                end %></td>
        <td><%= if league.user16_id != nil
                  User.find(league.user16_id).email 
                end %></td>
        <td><%= if league.user17_id != nil
                  User.find(league.user17_id).email 
                end %></td>
        <td><%= if league.user18_id != nil
                  User.find(league.user18_id).email 
                end %></td>
        <td><%= if league.user19_id != nil
                  User.find(league.user19_id).email 
                end %></td>
        <td><%= if league.user20_id != nil
                  User.find(league.user20_id).email 
                end %></td>
        <td><%= link_to 'Show', league %></td>
        <td><%= link_to 'Edit', edit_league_path(league) %></td>
        <td><%= link_to 'Destroy', league, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New League', new_league_path %>

app/views/leagues/new.html.erb
<h1>Create League</h1>
<% if user_signed_in? %>
    <%= render 'leagueForm' %>
    
    <%= link_to 'Back', leagues_path %>
<% end %> 

app/views/leagues/set_tiebreaker.html.haml
!!!
%html
  %head
  %body
    %h1{:align => "center", :class => "section_header"} #{@league_name} Tiebreaker
    %br
    = form_tag leagues_submit_tiebreaker_path(@league_id), :method => :post do
      %table.table-striped.container#games
        %thead
          %tr
            %th{:class => "span2", :align => "center"} Set Tiebreaker
            %th{:class => "span4", :align => "center"} Away
            %th{:class => "span2", :align => "center"}
            %th{:class => "span4", :align => "center"} Home

        %tbody
          - @games.each do |game|
            %tr.spaced
              %td{:class => "col-2", :align => "center"}
                = radio_button_tag "tiebreaker", "#{game.id}", false, class: "left", :onclick => "enableSubmit()"
              %td{:class => "col-3", :align => "center"} 
                %h3 #{game.away_team}
                - if game.away_odds > 0
                  %div.odds +#{game.away_odds}
                - else
                  %div.odds #{game.away_odds}
              %td{:class => "col-2", :align => "center"}
                %h6 #{game.game_time.in_time_zone("Eastern Time (US & Canada)").strftime("%m-%d-%Y %l:%M%p")} (ET)
                %h4 VS.<br /><br />
              %td{:class => "col-3", :align => "center"} 
                %h3 #{game.home_team} 
                - if game.home_odds > 0
                  %div.odds +#{game.home_odds}
                - else
                  %div.odds #{game.home_odds}
      %br
      %div.row
        %div.span12
          = submit_tag 'Set Tiebreaker', class: "btn btn-block", :disabled => true, id: "set_tiebreaker"

app/views/leagues/show.html.haml
%body
  %div.jumbotron
    %h2= @league.league_name 
  
  %br
  - if current_user.id==@league.commissioner_id && @tiebreaker == nil
    =button_to 'Set tiebreaker for this week', leagues_set_tiebreaker_path(@league), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold'
    
  - if @tiebreaker == nil || ((Time.now.in_time_zone("Central Time (US & Canada)").wday > 5) || Time.now.in_time_zone("Central Time (US & Canada)").wday < 3)
    =button_to 'Make picks for this week', games_picks_path(@league, @tiebreaker), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold', :disabled => 'true'
  - elsif (@league_pick == nil) && ((Time.now.in_time_zone("Central Time (US & Canada)").wday < 6) && Time.now.in_time_zone("Central Time (US & Canada)").wday > 2)
    =button_to 'Make picks for this week', games_picks_path(@league), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold', :id => "make_picks"
  
  - if ((Time.now.in_time_zone("Central Time (US & Canada)").wday > 5) || Time.now.in_time_zone("Central Time (US & Canada)").wday < 3)
    =button_to 'View everyone\'s picks for last week', show_all_picks_path(@league.id), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold'
    
  - elsif @league_pick != nil
    =button_to 'View your picks for this week', show_picks_path(@league.id, @current_user.id), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold'
    =button_to 'View everyone\'s picks for this week', show_all_picks_path(@league.id), :class => 'btn btn-default btn-block', :method => :get, :style => 'font-weight:bold'

  - if (@show_announcements)
    %br
    %p As an admin, you can create announcements that your leagues' other players can view:
    =button_to 'Create Announcement', leagues_add_announcements_path(@league), :class => 'btn btn-default', :method => :get
    
  %div.row
    %div.span12
      %hr
      %h3.section_header League Information
      %table
      - @infos.each do |info|
        %tr
          %td
            %strong= info[:title] + ": "
            = info[:data]
            %br
      %br
      - if current_user.id==@league.commissioner_id
        %td= link_to "Edit League Settings", edit_league_path
      %hr
      
  %div.row
    %div.span12
      %h3.section_header League Standings
      %table.table.table-striped
        %thead
          %tr
            %th
              %h5 Rank
            %th
              %h5 Name
            %th
              %h5 Wins
            %th
              %h5 Losses              
            %th
              %h5 Pushes
            -if ((Time.now.in_time_zone("Central Time (US & Canada)").wday > 5) || Time.now.in_time_zone("Central Time (US & Canada)").wday < 3)
              %th
                %h5 Last Week's Picks
            -else 
              %th
                %h5 This Week's Picks
        %tbody
          - @updated_standings.each do |player|
            %tr
              %td= player[:rank]
              %td= player[:name]
              %td= player[:wins]
              %td= player[:losses]
              %td= player[:pushes]
              - if (@league_pick != nil) || ((Time.now.in_time_zone("Central Time (US & Canada)").wday < 6) && Time.now.in_time_zone("Central Time (US & Canada)").wday > 2)
                %td= link_to "View", show_picks_path(@league.id, player[:id])
              - elsif ((Time.now.in_time_zone("Central Time (US & Canada)").wday > 5) || Time.now.in_time_zone("Central Time (US & Canada)").wday < 3)
                %td= link_to "View", show_picks_path(@league.id, player[:id])
              - else
                %td Not available yet!
      %hr
  
  %div.row
    %div.span12
      %h3.section_header Weekly Winners
      %table.table.table-striped
        %thead
          %tr
            %th
              %h5 Week Number
            %th
              %h5 Name
            %th
              %h6 Wins
            %th
              %h6 Losses
            %th
              %h6 Pushes
        %tbody
          - @season_weekly_winners.each do |winner|
            %tr
              %td= winner[:week_number]
              %td= winner[:name]
              %td= winner[:wins]
              %td= winner[:losses]
              %td= winner[:pushes]
      %hr
  
  = link_to 'Edit', edit_league_path(@league)
  |
  = link_to 'Back', authenticated_root_path