config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "leagues/accept_invite"
  post "leagues/add_user_to_league"
  resources :leagues
  resources :games
  resources :syncs
  resources :score_syncs
  
  get "users/sign_up"
  get "users/sign_in"
  get "users/about_page", as: :about_page

  post '/score_syncs/manualUpdate', to: 'score_syncs#manualUpdate', as: 'manualUpdate'
  
  get "games/picks/:league_id", to: 'games#picks', as: 'games_picks'
  post "games/submit_picks/:league_id", to: "games#submit_picks", as: "games_submit_picks"
  get "games/show_picks/:league_id/:user_id", to: 'games#show_picks', as: "show_picks"
  get "games/show_all_picks/:league_id", to: 'games#show_all_picks', as: "show_all_picks"
  
  get 'leagues/add_announcement/:league_id', to: 'leagues#add_announcement', as: 'leagues_add_announcements'
  get 'leagues/set_tiebreaker/:league_id', to:'leagues#set_tiebreaker', as: 'leagues_set_tiebreaker'
  post "games/submit_tiebreaker/:league_id", to: "leagues#submit_tiebreaker", as: "leagues_submit_tiebreaker"
  post 'leagues/create_announcement/:league_id', to: 'leagues#create_announcement', as: 'create_announcement'
end

app/models/sync.rb
# Contains all information on syncs coming from Pinnacle Sports.
class Sync < ActiveRecord::Base
    
end

app/controllers/syncs_controller.rb
# Used to simply display a list of all syncs in the database for administrator
# purposes. This is not end user facing.
#
# It can also be used to manually force a new sync to occur.
class SyncsController < ApplicationController
    
    skip_before_filter :authenticate_user!, :only => [:new]
    
    def index
        @syncs = Sync.all
    end
    
    def new
        GamesSync.perform
        flash[:notice] = "Finished new sync."
        redirect_to action: "index"
    end
    
end

app/views/syncs/index.html.haml
%h1 All Syncs

%table.container#syncs
  %thead
    %tr
      %th{:class => "col-2", :align => "center"} Sync Time
      %th{:class => "col-2", :align => "center"} New Games
      %th{:class => "col-2", :align => "center"} Updated Games
      %th{:class => "col-2", :align => "center"} Failed Games
      %th{:class => "col-2", :align => "center"} Successful?
      
  %tbody
    - @syncs.each do |sync|
      %tr
        %td{:class => "col-2", :align => "center"}= sync.timestamp
        %td{:class => "col-2", :align => "center"}= sync.new_games
        %td{:class => "col-2", :align => "center"}= sync.updated_games
        %td{:class => "col-2", :align => "center"}= sync.failed_games
        %td{:class => "col-2", :align => "center"}= sync.is_successful

%br
= button_to 'Force New Sync', new_sync_path, :method => :get, :id => "force_sync"