config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "leagues/accept_invite"
  post "leagues/add_user_to_league"
  resources :leagues
  resources :games
  resources :syncs
  resources :score_syncs
  
  get "users/sign_up"
  get "users/sign_in"
  get "users/about_page", as: :about_page

  post '/score_syncs/manualUpdate', to: 'score_syncs#manualUpdate', as: 'manualUpdate'
  
  get "games/picks/:league_id", to: 'games#picks', as: 'games_picks'
  post "games/submit_picks/:league_id", to: "games#submit_picks", as: "games_submit_picks"
  get "games/show_picks/:league_id/:user_id", to: 'games#show_picks', as: "show_picks"
  get "games/show_all_picks/:league_id", to: 'games#show_all_picks', as: "show_all_picks"
  
  get 'leagues/add_announcement/:league_id', to: 'leagues#add_announcement', as: 'leagues_add_announcements'
  get 'leagues/set_tiebreaker/:league_id', to:'leagues#set_tiebreaker', as: 'leagues_set_tiebreaker'
  post "games/submit_tiebreaker/:league_id", to: "leagues#submit_tiebreaker", as: "leagues_submit_tiebreaker"
  post 'leagues/create_announcement/:league_id', to: 'leagues#create_announcement', as: 'create_announcement'
end

app/models/game.rb
# Contains all information pertaining to Games saved in the database from 
# Pinnacle Sports.
class Game < ActiveRecord::Base
    
    def self.home_team_cover
        Game.all.each do |game|
            if (game.is_finished) then
                if((game.home_score+game.home_odds)==game.away_score)
                    game.homeTeamCover=1
                elsif ((game.home_score+game.home_odds)>game.away_score)
                    game.homeTeamCover=2
                else
                    game.homeTeamCover=0
                end
            end
            game.save!
        end
    end
end

app/controllers/games_controller.rb
# Used to simply display a list of all games in the database for administrator
# purposes. This is not end user facing.
class GamesController < ApplicationController
    
    def game_params
        params.require(:game).permit(:home_score, :away_score, :is_finished)
    end
    
    def index
        @games = Game.all
    end
    
    def edit
        @game = Game.find params[:id]
    end
    
    def update
        @game = Game.find params[:id]
        @game.update_attributes!(game_params)
        flash[:notice] = "#{@game.home_team} vs #{@game.away_team} was successfully updated."
        redirect_to games_path
    end
    
    def picks
        league = League.find(params[:league_id])
        #@tiebreaker = Tiebreaker.find(params[:tiebreaker_id])
        @num_picks = league.number_picks_settings;
        week = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%U')
        allGames = Game.all
        futureGames = []
        allGames.each do |game|
            if Time.now.utc < game.game_time.utc
                futureGames.push(game)
            end
        end
        @league_id = params[:league_id]
        
        @tiebreaker = Tiebreaker.where(league_id: league.id, week: week).take
        @tiebreaker_game = Game.where(id: @tiebreaker.game_id).take
        
        conference = league.conference_settings;
        games = []
        @games = []
        case conference
            when "SEC"
                teams = ["Alabama", "Arkansas", "Auburn", "Florida", "Georgia", "Kentucky", "LSU", "Mississippi St", "Missouri", "Mississippi", "South Carolina", "Tennessee U", "Texas A&M", "Vanderbilt"]
            when "Big 10"
                teams = ["Ohio State", "Michigan State", "Michigan", "Penn State", "Rutgers", "Indiana", "Maryland", "Iowa", "Wisconsin", "Northwestern", "Nebraska", "Illinois", "Minnesota U", "Purdue"]
            when "Big 12"
                teams = ["Oklahoma State", "Oklahoma", "TCU", "Baylor", "Texas", "Texas Tech", "West Virginia", "Iowa State", "Kansas State", "Kansas"]
            when "ACC"
                teams = ["Clemson", "Florida State", "Louisville", "NC State", "Syracuse", "Wake Forest", "Boston College", "North Carolina", "Pittsburgh U", "Miami Florida", "Duke", "Virginia Tech", "Virginia", "Georgia Tech"]
            when "American Athletic Conference"
                teams = ["Temple", "South Florida", "Cincinnati U", "Connecticut", "East Carolina", "UCF", "Houston", "Navy", "Memphis", "Tulsa", "Tulane", "SMU"]
            when "Conference USA"
                teams = ["Western Kentucky", "Marshall", "Middle Tennessee St", "Old Dominion", "Florida Intl", "Florida Atlantic", "Charlotte", "Louisiana Tech", "Southern Mississippi", "UTEP", "Rice", "Texas San Antonio", "North Texas"]
            when "Mid-American Conference"
                teams = ["Bowling Green", "Bowling Green", "Buffalo U", "Akron", "Kent State", "Massachusetts", "Miami Ohio", "Toledo", "Northern Illinois", "Western Michigan", "Central Michigan", "Ball State", "Eastern Michigan"]
            when "Mountain West Conference"
                teams = ["Air Force", "Boise State", "New Mexico", "Utah State", "Colorado State", "Wyoming", "San Diego State", "Nevada", "San Jose State", "UNLV", "Fresno State", "Hawaii"]
            when "PAC 12"
                teams = ["Stanford", "Oregon", "Washington State", "California", "Washington U", "Oregon State", "Utah", "USC", "UCLA", "Arizona State", "Arizona", "Colorado"]
            when "Sun Belt"
                teams = ["Arkansas State", "Appalachian State", "Georgia Southern", "South Alabama", "UL Lafayette", "Georgia State", "New Mexico State", "Troy", "Idaho", "Texas State", "UL Monroe"]
        end
        
        if conference == "FBS"
            @games = futureGames
        else
            futureGames.each do |game|
                teams.each do |team|
                    if game.home_team == team or game.away_team == team
                        games.push(game)
                    end
                end
            end
            @games = games.uniq{|game| game.id}
        end
        
        if @games.length < @num_picks
            @num_picks = @games.length
        end
    end
    
    def submit_picks
        league = League.find(params[:league_id])
        #tiebreaker = Tiebreaker.find(params[:tiebreaker_id])
        picks = params[:picks]
        week = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%U')
        tiebreaker = Tiebreaker.where(league_id: league.id, week: week).take
        @tiebreaker_game = Game.where(id: tiebreaker.game_id).take
        points_estimate = params[:tiebreaker]
        tiebreaker_game_id = @tiebreaker_game.id
        @picks = []
        
        league_pick = LeaguePick.create(:league_id => league.id, :user_id => current_user.id, :week => week, :wins => 0, :losses => 0, :pushes => 0)
        picks.each do |game_id, team_name|
            game = Game.find(game_id)
            pick = Pick.create(:game_id => game.id, :league_pick_id => league_pick.id, :home_wins => game.home_team == team_name)
            @picks << pick
        end
        
        TiebreakerPick.create(:game_id => tiebreaker_game_id, :league_pick_id => league_pick.id, :points_estimate => points_estimate)
        
        flash[:notice] = "Picks saved successfully!"
        redirect_to league_path(league)
    end
    
    def show_picks
        league = League.find(params[:league_id])
        #tiebreaker = Tiebreaker.find(params[:tiebreaker_id])
        @user = User.find(params[:user_id])
        week = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%U')
        day = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%w')
        #puts Time.now
        #puts day.to_i
        if(day.to_i < 3)
          my_picks = LeaguePick.where(league_id: league.id, user_id: current_user.id, week: week.to_i-1).take
          tiebreaker = Tiebreaker.where(league_id: league.id, week: week.to_i-1).take
          @league_pick = LeaguePick.where(league_id: league.id, user_id: @user.id, week: week.to_i-1).take
          
          if @league_pick == nil 
            render "games/no_picks"
            return
          end
        else
          my_picks = LeaguePick.where(league_id: league.id, user_id: current_user.id, week: week).take
          tiebreaker = Tiebreaker.where(league_id: league.id, week: week).take
          @league_pick = LeaguePick.where(league_id: league.id, user_id: @user.id, week: week).take
          
          if my_picks == nil && @user.id == current_user.id
            redirect_to games_picks_path(league)
            return
          elsif my_picks == nil
              render "games/make_my_picks_first"
              return
          end
          
          if @league_pick == nil 
            render "games/no_picks"
            return
          end
        end
        
        @tiebreaker_game = Game.where(id: tiebreaker.game_id).take
        @tiebreaker_pick = TiebreakerPick.where(league_pick_id: @league_pick.id).take
        
        @picks = Pick.where(league_pick_id: @league_pick.id).find_each
        @games = []
        
        @picks.each do |pick|
            game = Game.find(pick.game_id)
            @games << {
                :game => game, 
                :home_winner => pick.home_wins
            }
        end
    end
    
    def show_all_picks
        league = League.find(params[:league_id])
        week = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%U')
        day = Time.now.in_time_zone("Central Time (US & Canada)").strftime('%w')
        
        # list of members
        memberIds = [];
        memberIds << league.user1_id unless league.user1_id == nil
        memberIds << league.user2_id unless league.user2_id == nil
        memberIds << league.user3_id unless league.user3_id == nil
        memberIds << league.user4_id unless league.user4_id == nil
        memberIds << league.user5_id unless league.user5_id == nil
        memberIds << league.user6_id unless league.user6_id == nil
        memberIds << league.user7_id unless league.user7_id == nil
        memberIds << league.user8_id unless league.user8_id == nil
        memberIds << league.user9_id unless league.user9_id == nil
        memberIds << league.user10_id unless league.user10_id == nil
        memberIds << league.user11_id unless league.user11_id == nil
        memberIds << league.user12_id unless league.user12_id == nil
        memberIds << league.user13_id unless league.user13_id == nil
        memberIds << league.user14_id unless league.user14_id == nil
        memberIds << league.user15_id unless league.user15_id == nil
        memberIds << league.user16_id unless league.user16_id == nil
        memberIds << league.user17_id unless league.user17_id == nil
        memberIds << league.user18_id unless league.user18_id == nil
        memberIds << league.user19_id unless league.user19_id == nil
        memberIds << league.user20_id unless league.user20_id == nil
            
        @players = [];
        
        if day.to_i < 3
          tiebreaker = Tiebreaker.where(league_id: league.id, week: week.to_i-1).take
        else
          tiebreaker = Tiebreaker.where(league_id: league.id, week: week.to_i).take
        end
        
        if tiebreaker != nil
          @tiebreaker_game = Game.where(id: tiebreaker.game_id).take
        end

        memberIds.each do |user_id|
          user = User.find(user_id)
          if day.to_i < 3
            league_pick = LeaguePick.where(league_id: league.id, user_id: user.id, week: week.to_i-1).take
          else
            league_pick = LeaguePick.where(league_id: league.id, user_id: user.id, week: week.to_i).take
          end
          if league_pick != nil
              tiebreaker_pick = TiebreakerPick.where(league_pick_id: league_pick.id).take
              if(tiebreaker_pick != nil)

app/views/games/edit.html.haml
%h1 Edit Existing Game Score

= form_tag game_path(@game), :method => :put do

  Teams: #{@game.home_team} vs #{@game.away_team}<br/><br/>

  = label :game, :home_score, 'Home Score'
  = text_field :game, 'home_score'
  
  = label :game, :away_score, 'Away Score'
  = text_field :game, 'away_score'
  
  = label :game, :is_finished, 'Is Finished?'
  = select :game, :is_finished, [true, false]
  <br/><br/>
  
  = submit_tag 'Update Game Score', :id => "save"

app/views/games/index.html.haml
%h1 All Games

%table.container#games
  %thead
    %tr
      %th{:class => "col-2", :align => "center"} Game Time
      %th{:class => "col-2", :align => "center"} Home Team/Odds
      %th{:class => "col-2", :align => "center"} Away Team/Odds
      %th{:class => "col-2", :align => "center"} Home Team Score
      %th{:class => "col-2", :align => "center"} Away Team Score
      %th{:class => "col-2", :align => "center"} Finished?
      %th{:class => "col-2", :align => "center"} Edit?
      
  %tbody
    - @games.each do |game|
      %tr
        %td{:class => "col-2", :align => "center"}= game.game_time
        %td{:class => "col-2", :align => "center"} #{game.home_team} / #{game.home_odds}
        %td{:class => "col-2", :align => "center"} #{game.away_team} / #{game.away_odds}
        %td{:class => "col-2", :align => "center"}= game.home_score
        %td{:class => "col-2", :align => "center"}= game.away_score
        %td{:class => "col-2", :align => "center"}= game.is_finished
        %td{:class => "col-2", :align => "center", :id => "edit"}= link_to "edit", edit_game_path(game)

app/views/games/make_my_picks_first.haml
You need to make your picks before you can view other's!

app/views/games/no_picks.html.haml
This user hasn't made any picks yet!

app/views/games/picks.html.haml
!!!
%html
  %head
    = javascript_include_tag "picks.js"
  %body
    %h1{:align => "center", :class => "section_header"} #{current_user.first_name}'s Picks
    %br
    = form_tag games_submit_picks_path(@league_id, @tiebreaker), :method => :post do
      %table.table-striped.container#games
        %thead
          %tr
            %th{:class => "span2", :align => "center"} Pick 'Em
            %th{:class => "span3", :align => "center"} Away
            %th{:class => "span2", :align => "center"}
            %th{:class => "span3", :align => "center"} Home
            %th{:class => "span2", :align => "center"} Pick 'Em
            
        %tbody
          - @games.each do |game|
            %tr.spaced
              %td{:class => "col-2", :align => "center"}
                = radio_button_tag "picks[#{game.id}]", "#{game.away_team}", false, class: "left", :onclick => "radioCount(#{@num_picks})"
              %td{:class => "col-3", :align => "center"} 
                %h3 #{game.away_team}
                - if game.away_odds > 0
                  %div.odds +#{game.away_odds}
                - else
                  %div.odds #{game.away_odds}
              %td{:class => "col-2", :align => "center"}
                %h6 #{game.game_time.in_time_zone("Eastern Time (US & Canada)").strftime("%m-%d-%Y %l:%M%p")} (ET)
                %h4 VS.<br /><br />
                %button.btn{:type => "button", :onclick => "clearPick(#{game.id})", :id => "clearpick[#{game.id}]"} Clear Pick 
              %td{:class => "col-3", :align => "center"} 
                %h3 #{game.home_team} 
                - if game.home_odds > 0
                  %div.odds +#{game.home_odds}
                - else
                  %div.odds #{game.home_odds}
              %td{:class => "col-2", :align => "center"}
                = radio_button_tag "picks[#{game.id}]", "#{game.home_team}", false, class: "right", :onclick => "radioCount(#{@num_picks})"
      %br
      %h3{:align => "center", :class => "section_header"} Tiebreaker
      %table.table-striped.container#tiebreaker
        %thead
          %tr
            %th{:class => "span4", :align => "center"} Away
            %th{:class => "span2", :align => "center"}
            %th{:class => "span4", :align => "center"} Home
            %th{:class => "span2", :align => "center"} Predicted Points
            
        %tbody
          %tr.spaced
            %td{:class => "span4", :align => "center"} 
              %h3 #{@tiebreaker_game.away_team}
              - if @tiebreaker_game.away_odds > 0
                %div.odds +#{@tiebreaker_game.away_odds}
              - else
                %div.odds #{@tiebreaker_game.away_odds}
            %td{:class => "span2", :align => "center"}
              %h6 #{@tiebreaker_game.game_time.in_time_zone("Eastern Time (US & Canada)").strftime("%m-%d-%Y %l:%M%p")} (ET)
              %h4 VS.<br /><br />
            %td{:class => "span4", :align => "center"} 
              %h3 #{@tiebreaker_game.home_team} 
              - if @tiebreaker_game.home_odds > 0
                %div.odds +#{@tiebreaker_game.home_odds}
              - else
                %div.odds #{@tiebreaker_game.home_odds}
            %td{:class => "span2", :align => "center"}
              %input{:type=>"number", :required => true, :max => 999, :style => "width: 45px", :name => "tiebreaker"}
      %br
      %div.row
        %div.span12
          = submit_tag 'Submit Picks', class: "btn btn-block", :disabled => true, id: "submit_picks"
          

app/views/games/show_all_picks.html.haml
%body
  %div.row
    - @players.each do |player|
      %div.span3
        %h3.section_header.crop #{player[:name]}
        %table.container.table-striped.span3#games
          %thead
               
          %tbody
            - player[:games].each do |game|
              %tr
              - if game[:home_winner]
                - if game[:is_finished] &&(game[:correct_pick]==2)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold; color: green"}= game[:game].home_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: green;"}
                    - if game[:game].home_odds < 0
                      %div #{game[:game].home_odds}
                    - else
                      %div +#{game[:game].home_odds}
                - elsif game[:is_finished] &&(game[:correct_pick]==1)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold; color: yellow"}= game[:game].home_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: yellow;"}
                    - if game[:game].home_odds < 0
                      %div #{game[:game].home_odds}
                    - else
                      %div +#{game[:game].home_odds}
                - elsif game[:is_finished] &&(game[:correct_pick]==0)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: red; "}= game[:game].home_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: red;"}
                    - if game[:game].home_odds < 0
                      %div #{game[:game].home_odds}
                    - else
                      %div +#{game[:game].home_odds}
                - else
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;"}= game[:game].home_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;"}
                    - if game[:game].home_odds < 0
                      %div #{game[:game].home_odds}
                    - else
                      %div +#{game[:game].home_odds}
              - else
                - if game[:is_finished] &&(game[:correct_pick]==2)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color:green;"}= game[:game].away_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: green;"}
                    - if game[:game].away_odds < 0
                      %div #{game[:game].away_odds}
                    - else
                      %div +#{game[:game].away_odds}
                - elsif game[:is_finished] &&(game[:correct_pick]==1)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color:orange;"}= game[:game].away_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: orange;"}
                    - if game[:game].away_odds < 0
                      %div #{game[:game].away_odds}
                    - else
                      %div +#{game[:game].away_odds}
                - elsif game[:is_finished] &&(game[:correct_pick]==0)
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color:red;"}= game[:game].away_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;color: red;"}
                    - if game[:game].away_odds < 0
                      %div #{game[:game].away_odds}
                    - else
                      %div +#{game[:game].away_odds}
                - else
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;"}=game[:game].away_team
                  %td{:class => "col-1", :align => "left", :style => "font-weight: bold;"}
                    - if game[:game].away_odds < 0
                      %div #{game[:game].away_odds}
                    - else
                      %div +#{game[:game].away_odds}
        %br
        %p TIEBREAKER: #{player[:tiebreaker_pick].points_estimate}

app/views/games/show_picks.html.haml
%h1.section_header.jumbotron #{@user.first_name}'s Picks

%table.container.table-striped#games
  %thead
    %tr
      %th{:class => "col-2", :align => "center", :style => "text-decoration: underline; font-weight: normal;"} Away Odds
      %th{:class => "col-2", :align => "center", :style => "text-decoration: underline; font-weight: normal;"} Away Team
      %th{:class => "col-2", :align => "center", :style => "text-decoration: underline; font-weight: normal;"} Home Team
      %th{:class => "col-2", :align => "center", :style => "text-decoration: underline; font-weight: normal;"} Home Odds
     
  %tbody
    - @games.each do |game|
      %tr
        - if game[:home_winner]
          %td{:class => "col-2", :align => "center"}
            - if game[:game].away_odds < 0
              %div #{game[:game].away_odds}
            - else
              %div +#{game[:game].away_odds}
          %td{:class => "col-2", :align => "center"}= game[:game].away_team
          %td{:class => "col-2", :align => "center", :style => "font-weight: bold;"}= game[:game].home_team
          %td{:class => "col-2", :align => "center", :style => "font-weight: bold;"}
            - if game[:game].home_odds < 0
              %div #{game[:game].home_odds}
            - else
              %div +#{game[:game].home_odds}
        - else
          %td{:class => "col-2", :align => "center", :style => "font-weight: bold;"}
            - if game[:game].away_odds < 0
              %div #{game[:game].away_odds}
            - else
              %div +#{game[:game].away_odds}
          %td{:class => "col-2", :align => "center", :style => "font-weight: bold;"}= game[:game].away_team
          %td{:class => "col-2", :align => "center"}= game[:game].home_team
          %td{:class => "col-2", :align => "center"}
            - if game[:game].home_odds < 0
              %div #{game[:game].home_odds}
            - else
              %div +#{game[:game].home_odds}
%br
%p TIEBREAKER: #{@tiebreaker_game.home_team} vs. #{@tiebreaker_game.away_team}, Predicted Points: #{@tiebreaker_pick.points_estimate}