config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  
  devise_scope :user do
    authenticated :user do
      root 'users#index', as: :authenticated_root
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  get "leagues/accept_invite"
  post "leagues/add_user_to_league"
  resources :leagues
  resources :games
  resources :syncs
  resources :score_syncs
  
  get "users/sign_up"
  get "users/sign_in"
  get "users/about_page", as: :about_page

  post '/score_syncs/manualUpdate', to: 'score_syncs#manualUpdate', as: 'manualUpdate'
  
  get "games/picks/:league_id", to: 'games#picks', as: 'games_picks'
  post "games/submit_picks/:league_id", to: "games#submit_picks", as: "games_submit_picks"
  get "games/show_picks/:league_id/:user_id", to: 'games#show_picks', as: "show_picks"
  get "games/show_all_picks/:league_id", to: 'games#show_all_picks', as: "show_all_picks"
  
  get 'leagues/add_announcement/:league_id', to: 'leagues#add_announcement', as: 'leagues_add_announcements'
  get 'leagues/set_tiebreaker/:league_id', to:'leagues#set_tiebreaker', as: 'leagues_set_tiebreaker'
  post "games/submit_tiebreaker/:league_id", to: "leagues#submit_tiebreaker", as: "leagues_submit_tiebreaker"
  post 'leagues/create_announcement/:league_id', to: 'leagues#create_announcement', as: 'create_announcement'
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Pick 'Em
    = stylesheet_link_tag 'application', 'media' => 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js'
    = stylesheet_link_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/smoothness/jquery-ui.css"
    = javascript_include_tag 'https://code.jquery.com/jquery-migrate-1.1.1.js'
    = csrf_meta_tags

  %body
    %div.container
      %nav.navbar.nav-tabs.navbar-default{:role => "navigation"}
        .container-fluid
          %ul.nav
            %li
              - if !user_signed_in?
                = link_to "Home", authenticated_root_path, :id => 'home', :style => 'font-weight:bold'
              - else
                = link_to "Home", unauthenticated_root_path, :id => 'home', :style =>'font-weight:bold'
              - if !user_signed_in?
                %li
                  = link_to "Login", users_sign_in_path, :id => 'login', :style => 'font-weight:bold'
            %li
              = link_to "About Pick \'Em", about_page_path, :id => 'about_page', :style => 'font-weight:bold'
          %ul.nav.pull-right
            %li
              - if user_signed_in?
                = link_to "Logout", destroy_user_session_path, :method => :delete, :id => 'logout', :style => 'font-weight:bold'
        
      - if !notice.nil?
        %p.notice= notice
      
      - if !alert.nil?
        %p.alert= alert
        
      = yield